package com.example.core.model

enum class AuditAction(val label: String) {
    LOGIN_SUCCESS("Login Successful"),
    LOGIN_FAILED("Login Failed"),
    LOGOUT("User Logged Out"),
    ACCOUNT_LOCKED("Account Locked"),
    PASSWORD_CHANGED("Password Changed"),
    PASSWORD_RESET_REQUESTED("Password Reset Requested"),
    PATIENT_CREATED("Patient Registered"),
    PATIENT_UPDATED("Patient Record Updated"),
    PATIENT_VIEWED("Patient Record Accessed"),
    PATIENT_SEARCHED("Patient Directory Searched"),
    PATIENT_ARCHIVED("Patient Record Archived"),
    DUPLICATE_CHECK_PERFORMED("Duplicate Patient Check Evaluated"),
    APPOINTMENT_CREATED("Appointment Scheduled"),
    APPOINTMENT_CANCELLED("Appointment Cancelled"),
    APPOINTMENT_CHECKED_IN("Appointment Checked In"),
    QUEUE_TICKET_ISSUED("Queue Ticket Generated"),
    QUEUE_PATIENT_CALLED("Patient Called in Queue"),
    QUEUE_PATIENT_RECALLED("Patient Recalled in Queue"),
    QUEUE_PATIENT_SKIPPED("Patient Marked Skipped in Queue"),
    QUEUE_PATIENT_CANCELLED("Queue Ticket Cancelled"),
    QUEUE_PATIENT_TRANSFERRED("Queue Ticket Transferred"),
    QUEUE_DOCTOR_ASSIGNED("Doctor Assigned to Queue Ticket"),
    QUEUE_PRIORITY_CHANGED("Queue Priority Changed"),
    CONSULTATION_STARTED("Clinical Consultation Commenced"),
    CONSULTATION_COMPLETED("Clinical Consultation Concluded"),
    VITALS_RECORDED("Vital Signs Recorded"),
    CONSULTATION_CREATED("Clinical Consultation Saved"),
    PRESCRIPTION_ISSUED("Prescription Issued"),
    PRESCRIPTION_DISPENSED("Prescription Dispensed"),
    LAB_ORDER_CREATED("Lab Test Ordered"),
    LAB_RESULT_ENTERED("Lab Result Entered"),
    LAB_RESULT_VERIFIED("Lab Result Verified"),
    INVOICE_GENERATED("Billing Invoice Created"),
    PAYMENT_RECORDED("Payment Processed"),
    SETTINGS_UPDATED("Hospital Settings Changed"),
    UNAUTHORIZED_ACCESS_ATTEMPT("Unauthorized Access Blocked")
}

data class AuditLog(
    val id: String,
    val timestamp: Long,
    val userId: String?,
    val username: String?,
    val userRole: UserRole?,
    val action: AuditAction,
    val entityName: String,
    val entityId: String?,
    val details: String,
    val ipOrDevice: String,
    val result: String // "SUCCESS", "FAILURE", "BLOCKED"
)
